### ISSUE TITLE
Retrieve seedInfo fails if `shoot.status.technicalID` is not yet set

### ISSUE THREAD

**Issue by holgerkoser** [gardener/dashboard#1063]
**What happened**:
When creating a new shoot it is possible that the client retrieves the seedInfo before the status has been updated with the technicalID. The seedShootNamespace is initial 
https://github.com/gardener/dashboard/blob/master/backend/lib/services/shoots.js#L301 and the following attempt to assign the monitoring secret fails.

```
2021-07-20 07:37:19.884 error: failed to fetch monitoring-ingress-credentials secret: TypeError: The parameter "namespace" must be a string
    at assertNamespace (/usr/src/app/.yarn/cache/@gardener-dashboard-kube-client-workspace-5610037bb1-7.zip/node_modules/@gardener-dashboard/kube-client/lib/mixins.js:382:11)
    at Secret.get (/usr/src/app/.yarn/cache/@gardener-dashboard-kube-client-workspace-5610037bb1-7.zip/node_modules/@gardener-dashboard/kube-client/lib/mixins.js:82:5)
    at getSecret (/usr/src/app/lib/services/shoots.js:312:38)
    at assignMonitoringSecret (/usr/src/app/lib/services/shoots.js:324:24)
    at Object.exports.seedInfo (/usr/src/app/lib/services/shoots.js:302:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async /usr/src/app/lib/routes/shoots.js:179:16
2021-07-20 07:37:19.887 error: Failed to retrieve information using seed core client TypeError: The parameter "namespace" must be a string
    at assertNamespace (/usr/src/app/.yarn/cache/@gardener-dashboard-kube-client-workspace-5610037bb1-7.zip/node_modules/@gardener-dashboard/kube-client/lib/mixins.js:382:11)
    at Secret.get (/usr/src/app/.yarn/cache/@gardener-dashboard-kube-client-workspace-5610037bb1-7.zip/node_modules/@gardener-dashboard/kube-client/lib/mixins.js:82:5)
    at getSecret (/usr/src/app/lib/services/shoots.js:312:38)
    at assignMonitoringSecret (/usr/src/app/lib/services/shoots.js:324:24)
    at Object.exports.seedInfo (/usr/src/app/lib/services/shoots.js:302:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

**Comment by petersutter** [comment]
This issue can be closed if https://github.com/gardener/dashboard/issues/1318 is https://github.com/gardener/dashboard/issues/1318 is solved as the respective code will be deleted

**Comment by grolu** [comment]
/close
has already been fixed with https://github.com/gardener/dashboard/pull/1408
