### ISSUE TITLE
yarn serve fails with macOS Monterey

### ISSUE THREAD

**Issue by BeckerMax** [gardener/dashboard#1125]
**What happened**:
From the directory:
`~/go/src/github.com/gardener/dashboard/backend `
I executed:
`yarn serve`

Received error:
```
go/src/github.com/gardener/dashboard/.yarn/cache/universal-user-agent-npm-4.0.1-d1d67caaeb-553ee1f53f.zip/node_modules/universal-user-agent/dist-node/index.js:17
    throw error;
    ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at macosRelease (go/src/github.com/gardener/dashboard/.yarn/cache/macos-release-npm-2.4.1-4856441ab1-0d15f4b163.zip/node_modules/macos-release/index.js:26:26)
    at osName (/go/src/github.com/gardener/dashboard/.yarn/cache/os-name-npm-3.1.0-b5e3fb36cd-b4e5d61010.zip/node_modules/os-name/index.js:21:18)
    at getUserAgent (go/src/github.com/gardener/dashboard/.yarn/cache/universal-user-agent-npm-4.0.1-d1d67caaeb-553ee1f53f.zip/node_modules/universal-user-agent/dist-node/index.js:11:53)
    at parseOptions (go/src/github.com/gardener/dashboard/.yarn/cache/@octokit-rest-npm-16.43.2-dd2de884c3-d7a7a7cf5a.zip/node_modules/@octokit/rest/lib/parse-client-options.js:80:57)
    at Octokit (go/src/github.com/gardener/dashboard/.yarn/cache/@octokit-rest-npm-16.43.2-dd2de884c3-d7a7a7cf5a.zip/node_modules/@octokit/rest/lib/constructor.js:23:31)
    at init (go/src/github.com/gardener/dashboard/backend/lib/github/octokit.js:97:10)
    at Object.<anonymous> (go/src/github.com/gardener/dashboard/backend/lib/github/index.js:9:37)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
[nodemon] app crashed - waiting for file changes before starting...
```

**What you expected to happen**:
`yarn serve` to succeed on master with macOS Monterey

**How to reproduce it (as minimally and precisely as possible)**:
see above

**Anything else we need to know**:

As a caveat  I did not work with npm before.

What I tried to fix it:

run 
`yarn upgrade-interactive`
Update `@octokit/rest` from `16.28.1` to `16.43.2` which didn't help

I also updated it to `18.12.0` which caused other errors to appear.

I did this because the [macos-release](https://www.npmjs.com/package/macos-release) needs to be updated and if I read the stacktrace correctly it is transitively imported by octokit-rest.

**Environment**:
macOS Monterey 12.0.1
gardener/dashboard master

**Comment by grolu** [comment]
Thank you for reporting this. I will follow up us soon as I upgraded to Monterey. In the meantime feel free to further investigate :)

**Comment by BeckerMax** [comment]
👍🏼  @grolu I filed a PR to fix it
