### ISSUE TITLE
yarn serve "Couldn't find a script named "serve""

### ISSUE THREAD

**Issue by kmadac** [gardener/dashboard#1160]
**What happened**: I cloned the the dashboard repository and tried to start development version of dahsboard but it ends up with error:

```
Usage Error: Couldn't find a script named "serve".

$ yarn run [--inspect] [--inspect-brk] <scriptName> ...
```

**What you expected to happen**: start development version of frontend and backend version of gardenere dashboard

**How to reproduce it (as minimally and precisely as possible)**:

```
sudo curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update
sudo apt install yarn

git clone https://github.com/gardener/dashboard.git
cd dashboard
yarn serve
Usage Error: Couldn't find a script named "serve".

$ yarn run [--inspect] [--inspect-brk] <scriptName> ...
```

**Anything else we need to know**:

Cloned commit
```
commit 305d1f38d2bc95fb331ef33f6ac5728e31821b4b (HEAD -> master, origin/master, origin/HEAD)
Date:   Sun Feb 20 10:12:26 2022 +0200

    doc: Clean up old API version (#1156)
```

**Environment**:
OS  is Ubuntu  20.04. Yarn is in version 2.4.1

**Comment by petersutter** [comment]
you need to cd to the `dashboard/backend` and run `yarn serve` to run the backend server and cd to `dashboard/frontend` and run `yarn serve` there as well.

We need to improve the [`local-setup`](https://github.com/gardener/dashboard/blob/master/docs/development/local-setup.md) documentation

**Comment by kmadac** [comment]
Thank you very much. It helped.
Frontend is running :), but backend ends up with error

```
    this.ac = new AbortController()
                  ^

ReferenceError: AbortController is not defined
    at new LifecycleHooks (/home/kmadac/devel/grow2fit/t-systems/dashboard/backend/lib/hooks.js:19:19)
    at module.exports (/home/kmadac/devel/grow2fit/t-systems/dashboard/backend/lib/hooks.js:88:10)
    at Object.<anonymous> (/home/kmadac/devel/grow2fit/t-systems/dashboard/backend/lib/api.js:15:33)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at Function.external_module_.Module._load (/home/kmadac/devel/grow2fit/t-systems/dashboard/.pnp.js:27159:14)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/kmadac/devel/grow2fit/t-systems/dashboard/backend/lib/app.js:16:13)
``` 

But I suppose this is not problem with the yarn configuration so I'm closing the issue.

**Comment by petersutter** [comment]
did you ran `yarn` on the `dashboard` root? If not, do so :-)

**Comment by kmadac** [comment]
Yes I did run it. Just to be sure that everyhing is up to date, I just run it again, but it didn't help :(

**Comment by petersutter** [comment]
what is your `node` version?

**Comment by kmadac** [comment]
$ nodejs --version
v10.19.0

**Comment by kmadac** [comment]
thanks for mentioning nodejs version. I updated it to v16.14.0 and it works now :). Thank you veru much.
