### ISSUE TITLE
Couldn't add AWS secret from the dashboard

### ISSUE THREAD

**Issue by alban** [gardener/dashboard#86]
I tried to add a secret named `my-aws-secret` (default name). The dashboard printed the error `Request failed with status code 500`.

The logs:
```
$ kubectl logs  -n garden gardener-dashboard-59657bf588-x5qvm

2018-05-15T10:06:53.888Z - error: secretbindings.garden.sapcloud.io "my-aws-secret" is forbidden: secret "my-aws-secret" not found Error: secretbindings.garden.sapcloud.io "my-aws-secret" is forbidden: secret "my-aws-secret" not found
    at /usr/src/app/node_modules/kubernetes-client/lib/base.js:11:21
    at Request.request [as _callback] (/usr/src/app/node_modules/kubernetes-client/lib/request.js:65:7)
    at Request.self.callback (/usr/src/app/node_modules/kubernetes-client/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/src/app/node_modules/kubernetes-client/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/kubernetes-client/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
```

I tried with a different name and it worked fine.

Then I tried with the `my-aws-secret` name again, and it failed again. This time, the logs showed a different error:
```
$ kubectl logs  -n garden gardener-dashboard-59657bf588-x5qvm

2018-05-15T10:13:25.717Z - error: secrets "my-aws-secret" already exists Error: secrets "my-aws-secret" already exists
    at /usr/src/app/node_modules/kubernetes-client/lib/base.js:11:21
    at Request.request [as _callback] (/usr/src/app/node_modules/kubernetes-client/lib/request.js:65:7)
    at Request.self.callback (/usr/src/app/node_modules/kubernetes-client/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/src/app/node_modules/kubernetes-client/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/kubernetes-client/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
```

```
# kubectl get secretbindings -n garden-my-project  
NAME         AGE
verysecret   10m

# kubectl get secrets -n garden-my-project
NAME                     TYPE                                  DATA      AGE
albanclust.kubeconfig    Opaque                                6         8m
albanclust.ssh-keypair   Opaque                                2         8m
default-token-dzzph      kubernetes.io/service-account-token   3         12m
my-aws-secret            Opaque                                2         12m
verysecret               Opaque                                2         10m
```

The first secret `my-aws-secret` was actually created but it's maybe a timing issue. At the second attempt, it failed because it was already created.

**Comment by petersutter** [comment]
@rfranzke have you already removed the check for the existence of the secret?

**Comment by rfranzke** [comment]
No, but it's improved. The issue should not occur any longer as we not only rely on the cache anymore but do a live lookup in case we get 404 results.
